name: CI

on: 
  push:
    branches:
      - master

jobs:
  build:
    name: website build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: cache scala deps
        uses: coursier/cache-action@v6

      - name: Setup scala build chain
        uses: coursier/setup-action@v1
        with:
          jvm: adopt:11
          apps: sbtn

      - name: Setup node+yarn
        uses: actions/setup-node@v3

      - name: install yarn dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: test
        run: sbt test

      - name: prod build
        if: "contains(github.ref, 'master')"
        uses: borales/actions-yarn@v4
        with:
          cmd: run build

      - name: Deploy
        if: "success() && contains(github.ref, 'master')"
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
